import Head from "next/head";
import Image from "next/image";
import { useEffect, useState } from "react";
import styles from "../styles/Home.module.css";
import { Country, State, City } from "country-state-city";

export default function Home() {
  const [countryCode, setCountryCode] = useState("BD");
  const [selectedStates, setSelectedStates] = useState([]);
  const [isoCode, setsetIsoCode] = useState("13");
  const [selectedCities, setSelectedCities] = useState([]);

  const allCountries = Country.getAllCountries();

  useEffect(() => {
    const allStates = State.getStatesOfCountry(countryCode);
    setSelectedStates(allStates);
  }, [countryCode]);
  useEffect(() => {
    const allCities = City.getCitiesOfState(countryCode, isoCode);
    setSelectedCities(allCities);
  }, [isoCode]);
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className="container">
          <div style={{ paddingBottom: "20px" }}>
            <label>Country</label>
            <br />
            <select
              name="country"
              style={{ width: "200px" }}
              onChange={(e) => setCountryCode(e.target.value)}
            >
              <option>--Select--</option>

              {allCountries?.map((item, i) => {
                return (
                  <option value={item.isoCode} key={i}>
                    {item.name}
                  </option>
                );
              })}
            </select>
          </div>
          <div style={{ paddingBottom: "20px" }}>
            {isoCode}
            <label>State</label>
            <br />
            <select
              name="country"
              style={{ width: "200px" }}
              onChange={(e) => setsetIsoCode(e.target.value)}
            >
              <option>--Select--</option>
              {selectedStates.map((item, i) => {
                return (
                  <option value={item.isoCode} key={i}>
                    {item.name}
                  </option>
                );
              })}
            </select>
          </div>
          <div style={{ paddingBottom: "20px" }}>
            {isoCode}
            <label>City</label>
            <br />
            <select name="country" style={{ width: "200px" }}>
              <option>--Select--</option>
              {selectedCities.map((item, i) => {
                return (
                  <option value={item.isoCode} key={i}>
                    {item.name}
                  </option>
                );
              })}
            </select>
          </div>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
